import { supabase } from '@/lib/supabase'

// Per-session narratives generated by the narrate-session edge function.
// Used by the brief detail Story feed.
export const getSessionNarrativesForMicrosite = (micrositeId) =>
  supabase
    .from('microsite_session_narratives')
    .select(
      'id, session_id, microsite_id, fingerprint_id, narrative, signals, events_count, session_start, session_end, status, generated_at',
    )
    .eq('microsite_id', micrositeId)
    .eq('status', 'ready')
    .order('generated_at', { ascending: false })
